// <auto-generated />
using System;
using ERP.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERP.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260824081654_AddPosSalesModule")]
    partial class AddPosSalesModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ERP.Domain.Entities.InventoryTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("InventoryTransactions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccccccc-1111-1111-1111-111111111111"),
                            CreatedDate = new DateTime(2026, 1, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Okul açılış sezonu toptan A4 kağıt girişi",
                            IsDeleted = false,
                            ProductId = new Guid("bbbbbbbb-1111-1111-1111-111111111111"),
                            Quantity = 100,
                            TransactionDate = new DateTime(2026, 1, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            TransactionType = 1,
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-2222-2222-2222-222222222222"),
                            CreatedDate = new DateTime(2026, 1, 3, 14, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Atatürk Anadolu Lisesi kurumsal dönem başı sipariş sevkiyatı",
                            IsDeleted = false,
                            ProductId = new Guid("bbbbbbbb-1111-1111-1111-111111111111"),
                            Quantity = 50,
                            TransactionDate = new DateTime(2026, 1, 3, 14, 30, 0, 0, DateTimeKind.Utc),
                            TransactionType = 2,
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-3333-3333-3333-333333333333"),
                            CreatedDate = new DateTime(2026, 1, 4, 11, 15, 0, 0, DateTimeKind.Utc),
                            Description = "Kurumsal ofis sınav & test kalemi teslimatı",
                            IsDeleted = false,
                            ProductId = new Guid("bbbbbbbb-2222-2222-2222-222222222222"),
                            Quantity = 15,
                            TransactionDate = new DateTime(2026, 1, 4, 11, 15, 0, 0, DateTimeKind.Utc),
                            TransactionType = 2,
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-4444-4444-4444-444444444444"),
                            CreatedDate = new DateTime(2026, 1, 5, 16, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Depoda ambalajı hasar gören defter paketi düzeltmesi",
                            IsDeleted = false,
                            ProductId = new Guid("bbbbbbbb-3333-3333-3333-333333333333"),
                            Quantity = 2,
                            TransactionDate = new DateTime(2026, 1, 5, 16, 0, 0, 0, DateTimeKind.Utc),
                            TransactionType = 3,
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        });
                });

            modelBuilder.Entity("ERP.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentStock")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MinStockLevel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("SupplierId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-1111-1111-1111-111111111111"),
                            Code = "KRT-001",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStock = 8,
                            Description = "Yüksek beyazlıkta 80gr 2500 yaprak lazer/inkjet fotokopi kağıdı",
                            IsActive = true,
                            IsDeleted = false,
                            MinStockLevel = 25,
                            Name = "Copier Bond A4 80gr Fotokopi Kağıdı (5'li Koli)",
                            SupplierId = new Guid("dddddddd-2222-2222-2222-222222222222"),
                            Unit = "Koli",
                            UnitPrice = 780.00m
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-2222-2222-2222-222222222222"),
                            Code = "KRT-042",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStock = 5,
                            Description = "Özel SV yapıştırma kırılmaya dirençli sınav ve çizim kalemi",
                            IsActive = true,
                            IsDeleted = false,
                            MinStockLevel = 20,
                            Name = "Faber-Castell 2B Sınav Kurşun Kalem (72'li Kutu)",
                            SupplierId = new Guid("dddddddd-1111-1111-1111-111111111111"),
                            Unit = "Kutu",
                            UnitPrice = 360.00m
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-3333-3333-3333-333333333333"),
                            Code = "KRT-089",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStock = 12,
                            Description = "Sert kapak, mikroperforeli kaliteli 1. hamur kağıt okul ve ofis defteri",
                            IsActive = true,
                            IsDeleted = false,
                            MinStockLevel = 30,
                            Name = "Gıpta Spiralli A4 Çizgili Defter 96 Yaprak (10'lu Paket)",
                            SupplierId = new Guid("dddddddd-3333-3333-3333-333333333333"),
                            Unit = "Paket",
                            UnitPrice = 290.00m
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-4444-4444-4444-444444444444"),
                            Code = "KRT-114",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStock = 18,
                            Description = "Solventsiz, yıkanabilir ve kokusuz güçlü kırtasiye yapıştırıcı standı",
                            IsActive = true,
                            IsDeleted = false,
                            MinStockLevel = 10,
                            Name = "Pritt Stick Kuru Yapıştırıcı 43gr (24'lü Stand)",
                            SupplierId = new Guid("dddddddd-1111-1111-1111-111111111111"),
                            Unit = "Stand",
                            UnitPrice = 950.00m
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-5555-5555-5555-555555555555"),
                            Code = "KRT-205",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStock = 35,
                            Description = "Maksimum 25 sayfa kapasiteli metal iç mekanizmalı masaüstü zımba",
                            IsActive = true,
                            IsDeleted = false,
                            MinStockLevel = 10,
                            Name = "Maped Ağır Büro Zımba Makinesi No:24/6",
                            SupplierId = new Guid("dddddddd-1111-1111-1111-111111111111"),
                            Unit = "Adet",
                            UnitPrice = 175.00m
                        });
                });

            modelBuilder.Entity("ERP.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tam yetkili sistem yöneticisi",
                            IsDeleted = false,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Departman ve süreç yöneticisi",
                            IsDeleted = false,
                            Name = "Manager"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Standart sistem personeli",
                            IsDeleted = false,
                            Name = "Employee"
                        });
                });

            modelBuilder.Entity("ERP.Domain.Entities.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CashierUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FinalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CashierUserId");

                    b.HasIndex("ReceiptNumber")
                        .IsUnique();

                    b.ToTable("Sales", (string)null);
                });

            modelBuilder.Entity("ERP.Domain.Entities.SaleItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DiscountRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleItems", (string)null);
                });

            modelBuilder.Entity("ERP.Domain.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TaxNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Suppliers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("dddddddd-1111-1111-1111-111111111111"),
                            Address = "Saray Mah. Site Yolu Cad. No:5, Ümraniye/İstanbul",
                            ContactPerson = "Mehmet Yılmaz",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "siparis@adel.com.tr",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Adel Kalemcilik & Kırtasiye A.Ş.",
                            Phone = "+90 (216) 555 20 20",
                            TaxNumber = "0080012345"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-2222-2222-2222-222222222222"),
                            Address = "İkitelli OSB, Kağıtçılar Sanayi Sitesi 3. Cadde No:14, Başakşehir/İstanbul",
                            ContactPerson = "Ayşe Demir",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "satis@kopierkagit.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kopier A4 Kağıt & Ambalaj Sanayi Ltd.",
                            Phone = "+90 (212) 641 10 30",
                            TaxNumber = "5840987654"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-3333-3333-3333-333333333333"),
                            Address = "1. Organize Sanayi Bölgesi Dağıstan Cad. No:7, Sincan/Ankara",
                            ContactPerson = "Kemal Kaya",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "info@gipta.com.tr",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Gıpta Ofis & Okul Kırtasiye Ürünleri A.Ş.",
                            Phone = "+90 (312) 888 40 50",
                            TaxNumber = "4110456789"
                        });
                });

            modelBuilder.Entity("ERP.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@erp.com",
                            FullName = "Zehra Tuncer (Sistem Yöneticisi)",
                            IsActive = true,
                            IsDeleted = false,
                            PasswordHash = "$2a$11$q9o94O6k3Jb9vG6M2dYVn.6F1Z5x6i0q3pQ8nF5g8y8J6m5g8rK2W",
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("ERP.Domain.Entities.InventoryTransaction", b =>
                {
                    b.HasOne("ERP.Domain.Entities.Product", "Product")
                        .WithMany("Transactions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Product", b =>
                {
                    b.HasOne("ERP.Domain.Entities.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Sale", b =>
                {
                    b.HasOne("ERP.Domain.Entities.User", "CashierUser")
                        .WithMany()
                        .HasForeignKey("CashierUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CashierUser");
                });

            modelBuilder.Entity("ERP.Domain.Entities.SaleItem", b =>
                {
                    b.HasOne("ERP.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Entities.Sale", "Sale")
                        .WithMany("Items")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("ERP.Domain.Entities.User", b =>
                {
                    b.HasOne("ERP.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Product", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Sale", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Supplier", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
