// <auto-generated />
using System;
using ERP.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERP.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260827080516_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ERP.Domain.Entities.ApprovalHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ApproverUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("PurchaseRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StepNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApproverUserId");

                    b.HasIndex("PurchaseRequestId");

                    b.ToTable("ApprovalHistories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-1111-1111-1111-111111111111"),
                            Action = 1,
                            ActionDate = new DateTime(2026, 8, 26, 15, 30, 0, 0, DateTimeKind.Utc),
                            ApproverUserId = new Guid("aaaaaaaa-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Comment = "Okul açılışı öncesi defter stok gereksinimi onaylanmıştır.",
                            CreatedDate = new DateTime(2026, 8, 26, 15, 30, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            PurchaseRequestId = new Guid("88888888-2222-2222-2222-222222222222"),
                            StepName = "Birim / Şube Müdürü Onayı",
                            StepNumber = 1
                        },
                        new
                        {
                            Id = new Guid("55555555-2222-2222-2222-222222222222"),
                            Action = 2,
                            ActionDate = new DateTime(2026, 8, 25, 14, 0, 0, 0, DateTimeKind.Utc),
                            ApproverUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Comment = "Dönemlik bütçe aşımı sebebiyle lüks kalem talebi reddedilmiştir. Gelecek çeyrekte tekrar değerlendirilecektir.",
                            CreatedDate = new DateTime(2026, 8, 25, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            PurchaseRequestId = new Guid("88888888-3333-3333-3333-333333333333"),
                            StepName = "Genel Satın Alma Direktörü Onayı",
                            StepNumber = 2
                        },
                        new
                        {
                            Id = new Guid("55555555-3333-3333-3333-333333333333"),
                            Action = 1,
                            ActionDate = new DateTime(2026, 8, 24, 10, 0, 0, 0, DateTimeKind.Utc),
                            ApproverUserId = new Guid("aaaaaaaa-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Comment = "Standart büro malzeme ihtiyacı onaylandı.",
                            CreatedDate = new DateTime(2026, 8, 24, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            PurchaseRequestId = new Guid("88888888-4444-4444-4444-444444444444"),
                            StepName = "Birim / Şube Müdürü Onayı",
                            StepNumber = 1
                        });
                });

            modelBuilder.Entity("ERP.Domain.Entities.ApprovalStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApprovalWorkflowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MinAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StepNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalWorkflowId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("ApprovalSteps", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999992"),
                            ApprovalWorkflowId = new Guid("99999999-9999-9999-9999-999999999991"),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsRequired = true,
                            MaxAmount = 10000m,
                            MinAmount = 0m,
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222"),
                            StepName = "Birim / Şube Müdürü Onayı",
                            StepNumber = 1
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999993"),
                            ApprovalWorkflowId = new Guid("99999999-9999-9999-9999-999999999991"),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsRequired = true,
                            MinAmount = 10000.01m,
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            StepName = "Genel Satın Alma Direktörü Onayı",
                            StepNumber = 2
                        });
                });

            modelBuilder.Entity("ERP.Domain.Entities.ApprovalWorkflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ApprovalWorkflows", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999991"),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Limit bazlı kademeli kırtasiye satın alma onay iş akışı (10.000 TL altı Şube Müdürü, üzeri Genel Müdür/Direktör).",
                            IsActive = true,
                            IsDeleted = false,
                            MinAmount = 0m,
                            Name = "Standart Kırtasiye Onay Akışı"
                        });
                });

            modelBuilder.Entity("ERP.Domain.Entities.InventoryTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("InventoryTransactions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccccccc-1111-1111-1111-111111111111"),
                            CreatedDate = new DateTime(2026, 1, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Okul açılış sezonu toptan A4 fotokopi kağıdı mal kabul girişi",
                            IsDeleted = false,
                            ProductId = new Guid("bbbbbbbb-1111-1111-1111-111111111111"),
                            Quantity = 100,
                            TransactionDate = new DateTime(2026, 1, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            TransactionType = 1,
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-2222-2222-2222-222222222222"),
                            CreatedDate = new DateTime(2026, 1, 3, 14, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Atatürk Anadolu Lisesi kurumsal dönem başı sipariş sevkiyatı",
                            IsDeleted = false,
                            ProductId = new Guid("bbbbbbbb-1111-1111-1111-111111111111"),
                            Quantity = 50,
                            TransactionDate = new DateTime(2026, 1, 3, 14, 30, 0, 0, DateTimeKind.Utc),
                            TransactionType = 2,
                            UserId = new Guid("aaaaaaaa-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-3333-3333-3333-333333333333"),
                            CreatedDate = new DateTime(2026, 1, 4, 11, 15, 0, 0, DateTimeKind.Utc),
                            Description = "Kurumsal ofis sınav & test kalemi teslimatı",
                            IsDeleted = false,
                            ProductId = new Guid("bbbbbbbb-2222-2222-2222-222222222222"),
                            Quantity = 15,
                            TransactionDate = new DateTime(2026, 1, 4, 11, 15, 0, 0, DateTimeKind.Utc),
                            TransactionType = 2,
                            UserId = new Guid("aaaaaaaa-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-4444-4444-4444-444444444444"),
                            CreatedDate = new DateTime(2026, 1, 5, 16, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Depoda ambalajı hasar gören defter paketi düzeltmesi",
                            IsDeleted = false,
                            ProductId = new Guid("bbbbbbbb-3333-3333-3333-333333333333"),
                            Quantity = 2,
                            TransactionDate = new DateTime(2026, 1, 5, 16, 0, 0, 0, DateTimeKind.Utc),
                            TransactionType = 3,
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        });
                });

            modelBuilder.Entity("ERP.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("RoleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsRead");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-1111-1111-1111-111111111111"),
                            ActionUrl = "/inventory",
                            CreatedDate = new DateTime(2026, 8, 27, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsRead = false,
                            Message = "[KRT-001] Copier Bond A4 Kağıt stok miktarı (8 Koli) kritik eşik seviyesinin (25 Koli) altına düştü!",
                            RoleName = "Admin",
                            Title = "Kritik Stok Uyarısı",
                            Type = 3,
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("44444444-2222-2222-2222-222222222222"),
                            ActionUrl = "/purchasing",
                            CreatedDate = new DateTime(2026, 8, 27, 8, 30, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsRead = false,
                            Message = "TALEP-20260827-001 numaralı ve ₺14.500,00 tutarındaki satın alma talebi Genel Satın Alma Direktörü onayınızı beklemektedir.",
                            RoleName = "Admin",
                            Title = "Onayınızı Bekleyen Satın Alma Talebi",
                            Type = 4,
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("44444444-3333-3333-3333-333333333333"),
                            ActionUrl = "/inventory",
                            CreatedDate = new DateTime(2026, 8, 27, 8, 15, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsRead = false,
                            Message = "[KRT-042] Faber-Castell 2B Sınav Kurşun Kalem stok miktarı (5 Kutu) kritik eşik seviyesinin (20 Kutu) altına düştü!",
                            RoleName = "Manager",
                            Title = "Kritik Stok Uyarısı",
                            Type = 3,
                            UserId = new Guid("aaaaaaaa-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            ActionUrl = "/purchasing",
                            CreatedDate = new DateTime(2026, 8, 26, 15, 30, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsRead = true,
                            Message = "TALEP-20260826-002 numaralı satın alma talebiniz Şube Müdürü Ahmet Yılmaz tarafından onaylanmıştır.",
                            RoleName = "Employee",
                            Title = "Talep Onaylandı",
                            Type = 1,
                            UserId = new Guid("aaaaaaaa-cccc-cccc-cccc-cccccccccccc")
                        });
                });

            modelBuilder.Entity("ERP.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentStock")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MinStockLevel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("SupplierId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-1111-1111-1111-111111111111"),
                            Code = "KRT-001",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStock = 8,
                            Description = "Yüksek beyazlıkta 80gr 2500 yaprak lazer/inkjet fotokopi kağıdı",
                            IsActive = true,
                            IsDeleted = false,
                            MinStockLevel = 25,
                            Name = "Copier Bond A4 80gr Fotokopi Kağıdı (5'li Koli)",
                            SupplierId = new Guid("dddddddd-2222-2222-2222-222222222222"),
                            Unit = "Koli",
                            UnitPrice = 780.00m
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-2222-2222-2222-222222222222"),
                            Code = "KRT-042",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStock = 5,
                            Description = "Özel SV yapıştırma kırılmaya dirençli sınav ve çizim kalemi",
                            IsActive = true,
                            IsDeleted = false,
                            MinStockLevel = 20,
                            Name = "Faber-Castell 2B Sınav Kurşun Kalem (72'li Kutu)",
                            SupplierId = new Guid("dddddddd-1111-1111-1111-111111111111"),
                            Unit = "Kutu",
                            UnitPrice = 360.00m
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-3333-3333-3333-333333333333"),
                            Code = "KRT-089",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStock = 12,
                            Description = "Sert kapak, mikroperforeli kaliteli 1. hamur kağıt okul ve ofis defteri",
                            IsActive = true,
                            IsDeleted = false,
                            MinStockLevel = 30,
                            Name = "Gıpta Spiralli A4 Çizgili Defter 96 Yaprak (10'lu Paket)",
                            SupplierId = new Guid("dddddddd-3333-3333-3333-333333333333"),
                            Unit = "Paket",
                            UnitPrice = 290.00m
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-4444-4444-4444-444444444444"),
                            Code = "KRT-114",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStock = 24,
                            Description = "Solventsiz, yıkanabilir ve kokusuz güçlü kırtasiye yapıştırıcı standı",
                            IsActive = true,
                            IsDeleted = false,
                            MinStockLevel = 10,
                            Name = "Pritt Stick Kuru Yapıştırıcı 43gr (24'lü Stand)",
                            SupplierId = new Guid("dddddddd-4444-4444-4444-444444444444"),
                            Unit = "Stand",
                            UnitPrice = 950.00m
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-5555-5555-5555-555555555555"),
                            Code = "KRT-205",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStock = 35,
                            Description = "Maksimum 25 sayfa kapasiteli metal iç mekanizmalı masaüstü zımba",
                            IsActive = true,
                            IsDeleted = false,
                            MinStockLevel = 10,
                            Name = "Maped Ağır Büro Zımba Makinesi No:24/6",
                            SupplierId = new Guid("dddddddd-5555-5555-5555-555555555555"),
                            Unit = "Adet",
                            UnitPrice = 175.00m
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-6666-6666-6666-666666666666"),
                            Code = "KRT-301",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStock = 45,
                            Description = "Canlı ve parlak renkler, yüksek örtücülük, çocuklara özel toksik olmayan formül",
                            IsActive = true,
                            IsDeleted = false,
                            MinStockLevel = 15,
                            Name = "Faber-Castell 24'lü Suluboya & Fırça Seti",
                            SupplierId = new Guid("dddddddd-1111-1111-1111-111111111111"),
                            Unit = "Set",
                            UnitPrice = 210.00m
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-7777-7777-7777-777777777777"),
                            Code = "KRT-401",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStock = 18,
                            Description = "Ortopedik sırt desteği, su geçirmez kumaş ve çok bölmeli geniş hacim",
                            IsActive = true,
                            IsDeleted = false,
                            MinStockLevel = 8,
                            Name = "Yaygan Lisanslı Ergonomik Okul Sırt Çantası",
                            SupplierId = new Guid("dddddddd-3333-3333-3333-333333333333"),
                            Unit = "Adet",
                            UnitPrice = 850.00m
                        });
                });

            modelBuilder.Entity("ERP.Domain.Entities.PurchaseRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentApprovalStep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("RequestNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("RequesterUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RequiredDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalEstimatedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RequestNumber")
                        .IsUnique();

                    b.HasIndex("RequesterUserId");

                    b.ToTable("PurchaseRequests", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("88888888-1111-1111-1111-111111111111"),
                            CreatedDate = new DateTime(2026, 8, 27, 8, 30, 0, 0, DateTimeKind.Utc),
                            CurrentApprovalStep = 2,
                            Department = "Merkez Mağaza Satış & Depo",
                            IsDeleted = false,
                            Note = "Kritik stok seviyesine düşen A4 fotokopi kağıdı ve kurşun kalemler için acil tedarik talebi.",
                            Priority = 2,
                            RequestNumber = "TALEP-20260827-001",
                            RequesterUserId = new Guid("aaaaaaaa-cccc-cccc-cccc-cccccccccccc"),
                            Status = 2,
                            TotalEstimatedAmount = 14500.00m
                        },
                        new
                        {
                            Id = new Guid("88888888-2222-2222-2222-222222222222"),
                            CreatedDate = new DateTime(2026, 8, 26, 14, 0, 0, 0, DateTimeKind.Utc),
                            CurrentApprovalStep = 1,
                            Department = "Okul & Kurumsal Satış",
                            IsDeleted = false,
                            Note = "Gıpta spiralli defter stok takviyesi (Onaylandı - Mal kabul yapılabilir).",
                            Priority = 2,
                            RequestNumber = "TALEP-20260826-002",
                            RequesterUserId = new Guid("aaaaaaaa-cccc-cccc-cccc-cccccccccccc"),
                            Status = 3,
                            TotalEstimatedAmount = 5800.00m
                        },
                        new
                        {
                            Id = new Guid("88888888-3333-3333-3333-333333333333"),
                            CreatedDate = new DateTime(2026, 8, 25, 11, 20, 0, 0, DateTimeKind.Utc),
                            CurrentApprovalStep = 2,
                            Department = "Yönetim & İdari İşler",
                            IsDeleted = false,
                            Note = "Lüks dolmakalem ve özel masaüstü deri setleri talebi.",
                            Priority = 2,
                            RequestNumber = "TALEP-20260825-003",
                            RequesterUserId = new Guid("aaaaaaaa-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Status = 4,
                            TotalEstimatedAmount = 25500.00m
                        },
                        new
                        {
                            Id = new Guid("88888888-4444-4444-4444-444444444444"),
                            CreatedDate = new DateTime(2026, 8, 24, 9, 15, 0, 0, DateTimeKind.Utc),
                            CurrentApprovalStep = 1,
                            Department = "Merkez Mağaza Satış & Depo",
                            IsDeleted = false,
                            Note = "Pritt yapıştırıcı ve zımba makinesi dönem başı siparişi (Depoya teslim alındı).",
                            Priority = 2,
                            RequestNumber = "TALEP-20260824-004",
                            RequesterUserId = new Guid("aaaaaaaa-cccc-cccc-cccc-cccccccccccc"),
                            Status = 5,
                            TotalEstimatedAmount = 8750.00m
                        });
                });

            modelBuilder.Entity("ERP.Domain.Entities.PurchaseRequestItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EstimatedTotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EstimatedUnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PurchaseRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RequestedQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseRequestId");

                    b.ToTable("PurchaseRequestItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("66666666-1111-1111-1111-111111111111"),
                            CreatedDate = new DateTime(2026, 8, 27, 8, 30, 0, 0, DateTimeKind.Utc),
                            EstimatedTotalPrice = 11700.00m,
                            EstimatedUnitPrice = 780.00m,
                            IsDeleted = false,
                            Notes = "Fotokopi kağıdı tükenmek üzere, acil sevk gerekli",
                            ProductId = new Guid("bbbbbbbb-1111-1111-1111-111111111111"),
                            PurchaseRequestId = new Guid("88888888-1111-1111-1111-111111111111"),
                            RequestedQuantity = 15,
                            Unit = "Koli"
                        },
                        new
                        {
                            Id = new Guid("66666666-2222-2222-2222-222222222222"),
                            CreatedDate = new DateTime(2026, 8, 27, 8, 30, 0, 0, DateTimeKind.Utc),
                            EstimatedTotalPrice = 2800.00m,
                            EstimatedUnitPrice = 280.00m,
                            IsDeleted = false,
                            Notes = "Sınav haftası için 2B kurşun kalem desteği",
                            ProductId = new Guid("bbbbbbbb-2222-2222-2222-222222222222"),
                            PurchaseRequestId = new Guid("88888888-1111-1111-1111-111111111111"),
                            RequestedQuantity = 10,
                            Unit = "Kutu"
                        },
                        new
                        {
                            Id = new Guid("66666666-3333-3333-3333-333333333333"),
                            CreatedDate = new DateTime(2026, 8, 26, 14, 0, 0, 0, DateTimeKind.Utc),
                            EstimatedTotalPrice = 5800.00m,
                            EstimatedUnitPrice = 290.00m,
                            IsDeleted = false,
                            Notes = "Okul açılış sezonu defter takviyesi",
                            ProductId = new Guid("bbbbbbbb-3333-3333-3333-333333333333"),
                            PurchaseRequestId = new Guid("88888888-2222-2222-2222-222222222222"),
                            RequestedQuantity = 20,
                            Unit = "Paket"
                        },
                        new
                        {
                            Id = new Guid("66666666-4444-4444-4444-444444444444"),
                            CreatedDate = new DateTime(2026, 8, 24, 9, 15, 0, 0, DateTimeKind.Utc),
                            EstimatedTotalPrice = 8750.00m,
                            EstimatedUnitPrice = 175.00m,
                            IsDeleted = false,
                            Notes = "Kurumsal büro zımba teslimatı yapıldı",
                            ProductId = new Guid("bbbbbbbb-5555-5555-5555-555555555555"),
                            PurchaseRequestId = new Guid("88888888-4444-4444-4444-444444444444"),
                            RequestedQuantity = 50,
                            Unit = "Adet"
                        });
                });

            modelBuilder.Entity("ERP.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tam yetkili sistem yöneticisi",
                            IsDeleted = false,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Departman ve süreç yöneticisi",
                            IsDeleted = false,
                            Name = "Manager"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Standart sistem personeli",
                            IsDeleted = false,
                            Name = "Employee"
                        });
                });

            modelBuilder.Entity("ERP.Domain.Entities.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CashierUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FinalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CashierUserId");

                    b.HasIndex("ReceiptNumber")
                        .IsUnique();

                    b.ToTable("Sales", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("77777777-1111-1111-1111-111111111111"),
                            CashierUserId = new Guid("aaaaaaaa-cccc-cccc-cccc-cccccccccccc"),
                            CreatedDate = new DateTime(2026, 8, 27, 9, 15, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Mehmet Demir (Perakende Müşteri)",
                            DiscountAmount = 0.00m,
                            FinalAmount = 940.00m,
                            IsDeleted = false,
                            PaymentMethod = 1,
                            ReceiptNumber = "FIS-20260827-001",
                            SaleDate = new DateTime(2026, 8, 27, 9, 15, 0, 0, DateTimeKind.Utc),
                            TotalAmount = 940.00m
                        },
                        new
                        {
                            Id = new Guid("77777777-2222-2222-2222-222222222222"),
                            CashierUserId = new Guid("aaaaaaaa-cccc-cccc-cccc-cccccccccccc"),
                            CreatedDate = new DateTime(2026, 8, 27, 10, 30, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Ayşe Yılmaz (Öğrenci Velisi)",
                            DiscountAmount = 0.00m,
                            FinalAmount = 1060.00m,
                            IsDeleted = false,
                            PaymentMethod = 2,
                            ReceiptNumber = "FIS-20260827-002",
                            SaleDate = new DateTime(2026, 8, 27, 10, 30, 0, 0, DateTimeKind.Utc),
                            TotalAmount = 1060.00m
                        },
                        new
                        {
                            Id = new Guid("77777777-3333-3333-3333-333333333333"),
                            CashierUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedDate = new DateTime(2026, 8, 26, 16, 45, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Özel Bilim Koleji (Kurumsal)",
                            DiscountAmount = 0.00m,
                            FinalAmount = 4250.00m,
                            IsDeleted = false,
                            PaymentMethod = 1,
                            ReceiptNumber = "FIS-20260826-003",
                            SaleDate = new DateTime(2026, 8, 26, 16, 45, 0, 0, DateTimeKind.Utc),
                            TotalAmount = 4250.00m
                        });
                });

            modelBuilder.Entity("ERP.Domain.Entities.SaleItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DiscountRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-1111-1111-1111-111111111111"),
                            CreatedDate = new DateTime(2026, 8, 27, 9, 15, 0, 0, DateTimeKind.Utc),
                            DiscountRate = 0.00m,
                            IsDeleted = false,
                            ProductId = new Guid("bbbbbbbb-2222-2222-2222-222222222222"),
                            Quantity = 1,
                            SaleId = new Guid("77777777-1111-1111-1111-111111111111"),
                            TotalPrice = 360.00m,
                            UnitPrice = 360.00m
                        },
                        new
                        {
                            Id = new Guid("33333333-2222-2222-2222-222222222222"),
                            CreatedDate = new DateTime(2026, 8, 27, 9, 15, 0, 0, DateTimeKind.Utc),
                            DiscountRate = 0.00m,
                            IsDeleted = false,
                            ProductId = new Guid("bbbbbbbb-3333-3333-3333-333333333333"),
                            Quantity = 2,
                            SaleId = new Guid("77777777-1111-1111-1111-111111111111"),
                            TotalPrice = 580.00m,
                            UnitPrice = 290.00m
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedDate = new DateTime(2026, 8, 27, 10, 30, 0, 0, DateTimeKind.Utc),
                            DiscountRate = 0.00m,
                            IsDeleted = false,
                            ProductId = new Guid("bbbbbbbb-7777-7777-7777-777777777777"),
                            Quantity = 1,
                            SaleId = new Guid("77777777-2222-2222-2222-222222222222"),
                            TotalPrice = 850.00m,
                            UnitPrice = 850.00m
                        },
                        new
                        {
                            Id = new Guid("33333333-4444-4444-4444-444444444444"),
                            CreatedDate = new DateTime(2026, 8, 27, 10, 30, 0, 0, DateTimeKind.Utc),
                            DiscountRate = 0.00m,
                            IsDeleted = false,
                            ProductId = new Guid("bbbbbbbb-6666-6666-6666-666666666666"),
                            Quantity = 1,
                            SaleId = new Guid("77777777-2222-2222-2222-222222222222"),
                            TotalPrice = 210.00m,
                            UnitPrice = 210.00m
                        },
                        new
                        {
                            Id = new Guid("33333333-5555-5555-5555-555555555555"),
                            CreatedDate = new DateTime(2026, 8, 26, 16, 45, 0, 0, DateTimeKind.Utc),
                            DiscountRate = 0.00m,
                            IsDeleted = false,
                            ProductId = new Guid("bbbbbbbb-1111-1111-1111-111111111111"),
                            Quantity = 5,
                            SaleId = new Guid("77777777-3333-3333-3333-333333333333"),
                            TotalPrice = 3900.00m,
                            UnitPrice = 780.00m
                        },
                        new
                        {
                            Id = new Guid("33333333-6666-6666-6666-666666666666"),
                            CreatedDate = new DateTime(2026, 8, 26, 16, 45, 0, 0, DateTimeKind.Utc),
                            DiscountRate = 0.00m,
                            IsDeleted = false,
                            ProductId = new Guid("bbbbbbbb-5555-5555-5555-555555555555"),
                            Quantity = 2,
                            SaleId = new Guid("77777777-3333-3333-3333-333333333333"),
                            TotalPrice = 350.00m,
                            UnitPrice = 175.00m
                        });
                });

            modelBuilder.Entity("ERP.Domain.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TaxNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Suppliers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("dddddddd-1111-1111-1111-111111111111"),
                            Address = "Saray Mah. Site Yolu Cad. No:5, Ümraniye/İstanbul",
                            ContactPerson = "Mehmet Yılmaz",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "siparis@adel.com.tr",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Adel Kalemcilik & Kırtasiye A.Ş.",
                            Phone = "+90 (216) 555 20 20",
                            TaxNumber = "0080012345"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-2222-2222-2222-222222222222"),
                            Address = "İkitelli OSB, Kağıtçılar Sanayi Sitesi 3. Cadde No:14, Başakşehir/İstanbul",
                            ContactPerson = "Ayşe Demir",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "satis@kopierkagit.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kopier A4 Kağıt & Ambalaj Sanayi Ltd.",
                            Phone = "+90 (212) 641 10 30",
                            TaxNumber = "5840987654"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-3333-3333-3333-333333333333"),
                            Address = "1. Organize Sanayi Bölgesi Dağıstan Cad. No:7, Sincan/Ankara",
                            ContactPerson = "Kemal Kaya",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "info@gipta.com.tr",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Gıpta Ofis & Okul Kırtasiye Ürünleri A.Ş.",
                            Phone = "+90 (312) 888 40 50",
                            TaxNumber = "4110456789"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-4444-4444-4444-444444444444"),
                            Address = "Dudullu OSB Baraj Yolu No:28, Ümraniye/İstanbul",
                            ContactPerson = "Canan Öztürk",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "tedarik@fabercastell.com.tr",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Faber-Castell & Daksil Dağıtım A.Ş.",
                            Phone = "+90 (216) 420 80 90",
                            TaxNumber = "3201847192"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-5555-5555-5555-555555555555"),
                            Address = "Kemankeş Karamustafapaşa Mah. Rıhtım Cad. No:19, Beyoğlu/İstanbul",
                            ContactPerson = "Serdar Aksoy",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "iletisim@mapedturkiye.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Maped & Büro Araçları Tic. Ltd. Şti.",
                            Phone = "+90 (212) 243 70 80",
                            TaxNumber = "1892049182"
                        });
                });

            modelBuilder.Entity("ERP.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@erp.com",
                            FullName = "Zehra Tuncer (Sistem Yöneticisi)",
                            IsActive = true,
                            IsDeleted = false,
                            PasswordHash = "$2a$11$q9o94O6k3Jb9vG6M2dYVn.6F1Z5x6i0q3pQ8nF5g8y8J6m5g8rK2W",
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "manager@erp.com",
                            FullName = "Ahmet Yılmaz (Kırtasiye & Şube Müdürü)",
                            IsActive = true,
                            IsDeleted = false,
                            PasswordHash = "$2a$11$q9o94O6k3Jb9vG6M2dYVn.6F1Z5x6i0q3pQ8nF5g8y8J6m5g8rK2W",
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-cccc-cccc-cccc-cccccccccccc"),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "kasiyer@erp.com",
                            FullName = "Elif Kaya (Kasa & Satış Personeli)",
                            IsActive = true,
                            IsDeleted = false,
                            PasswordHash = "$2a$11$q9o94O6k3Jb9vG6M2dYVn.6F1Z5x6i0q3pQ8nF5g8y8J6m5g8rK2W",
                            RoleId = new Guid("33333333-3333-3333-3333-333333333333")
                        });
                });

            modelBuilder.Entity("ERP.Domain.Entities.ApprovalHistory", b =>
                {
                    b.HasOne("ERP.Domain.Entities.User", "ApproverUser")
                        .WithMany()
                        .HasForeignKey("ApproverUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ERP.Domain.Entities.PurchaseRequest", "PurchaseRequest")
                        .WithMany("ApprovalHistories")
                        .HasForeignKey("PurchaseRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApproverUser");

                    b.Navigation("PurchaseRequest");
                });

            modelBuilder.Entity("ERP.Domain.Entities.ApprovalStep", b =>
                {
                    b.HasOne("ERP.Domain.Entities.ApprovalWorkflow", "ApprovalWorkflow")
                        .WithMany("Steps")
                        .HasForeignKey("ApprovalWorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ERP.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApprovalWorkflow");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ERP.Domain.Entities.InventoryTransaction", b =>
                {
                    b.HasOne("ERP.Domain.Entities.Product", "Product")
                        .WithMany("Transactions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Notification", b =>
                {
                    b.HasOne("ERP.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Product", b =>
                {
                    b.HasOne("ERP.Domain.Entities.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ERP.Domain.Entities.PurchaseRequest", b =>
                {
                    b.HasOne("ERP.Domain.Entities.User", "RequesterUser")
                        .WithMany()
                        .HasForeignKey("RequesterUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RequesterUser");
                });

            modelBuilder.Entity("ERP.Domain.Entities.PurchaseRequestItem", b =>
                {
                    b.HasOne("ERP.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Entities.PurchaseRequest", "PurchaseRequest")
                        .WithMany("Items")
                        .HasForeignKey("PurchaseRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("PurchaseRequest");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Sale", b =>
                {
                    b.HasOne("ERP.Domain.Entities.User", "CashierUser")
                        .WithMany()
                        .HasForeignKey("CashierUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CashierUser");
                });

            modelBuilder.Entity("ERP.Domain.Entities.SaleItem", b =>
                {
                    b.HasOne("ERP.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Entities.Sale", "Sale")
                        .WithMany("Items")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("ERP.Domain.Entities.User", b =>
                {
                    b.HasOne("ERP.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ERP.Domain.Entities.ApprovalWorkflow", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Product", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ERP.Domain.Entities.PurchaseRequest", b =>
                {
                    b.Navigation("ApprovalHistories");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Sale", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ERP.Domain.Entities.Supplier", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
